import { Badge } from "@/components/ui/badge"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table"
import { trades } from "@/data/mockData"

function ActionBadge({ action }: { action: string }) {
  if (action === "BUY") {
    return <Badge className="rounded-full">BUY</Badge>
  }

  if (action === "SELL") {
    return (
      <Badge variant="destructive" className="rounded-full">
        SELL
      </Badge>
    )
  }

  return (
    <Badge variant="secondary" className="rounded-full">
      HOLD
    </Badge>
  )
}

export default function Trades() {
  return (
    <div className="space-y-6">
      <header className="space-y-2">
        <div className="flex items-center gap-3">
          <h1 className="text-3xl font-bold tracking-tight text-slate-900">
            Trades
          </h1>
          <Badge variant="secondary" className="rounded-full">
            Execution History
          </Badge>
        </div>
        <p className="text-slate-600">
          Recent buy, sell, and hold actions generated by PortaAI.
        </p>
      </header>

      <Card className="rounded-2xl border-slate-200 shadow-sm">
        <CardHeader>
          <CardTitle>Recent Trades</CardTitle>
        </CardHeader>
        <CardContent>
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Asset</TableHead>
                <TableHead>Action</TableHead>
                <TableHead>Amount</TableHead>
                <TableHead>Time</TableHead>
                <TableHead>Status</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {trades.map((trade, index) => (
                <TableRow key={`${trade.asset}-${index}`}>
                  <TableCell className="font-medium">{trade.asset}</TableCell>
                  <TableCell>
                    <ActionBadge action={trade.action} />
                  </TableCell>
                  <TableCell>${trade.amount.toFixed(2)}</TableCell>
                  <TableCell>{trade.time}</TableCell>
                  <TableCell>
                    <Badge className="rounded-full bg-cyan-600 hover:bg-cyan-600">
                      {trade.status}
                    </Badge>
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </CardContent>
      </Card>

      <Card className="rounded-2xl border-slate-200 shadow-sm">
        <CardHeader>
          <CardTitle>Trade Summary</CardTitle>
        </CardHeader>
        <CardContent>
          <p className="text-slate-600">
            Each trade shown here is generated by the portfolio decision engine
            after combining model forecasts, sentiment signals, and portfolio
            allocation rules. In the current implementation, execution is
            simulated as part of paper trading.
          </p>
        </CardContent>
      </Card>
    </div>
  )
}