import { Badge } from "@/components/ui/badge"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table"
import { apiFetch } from "@/lib/api"
import { useEffect, useState } from "react"

type Trade = {
  asset: string
  action: string
  amount: number
  time: string
  status: string
}

type TradesResponse = {
  portfolio_id: number
  trades: Trade[]
}

function ActionBadge({ action }: { action: string }) {
  if (action === "BUY") {
    return (
      <Badge className="rounded-full bg-emerald-600 hover:bg-emerald-700">
        BUY
      </Badge>
    )
  }

  if (action === "SELL") {
    return (
      <Badge className="rounded-full bg-red-600 hover:bg-red-700">
        SELL
      </Badge>
    )
  }

  return (
    <Badge className="rounded-full bg-slate-200 text-slate-700 hover:bg-slate-200">
      HOLD
    </Badge>
  )
}

function formatCurrency(value: number) {
  return `$${value.toLocaleString(undefined, {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  })}`
}

export default function Trades() {
  const [trades, setTrades] = useState<Trade[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)

  useEffect(() => {
    async function fetchTrades(showLoading = false) {
      try {
        if (showLoading) {
          setLoading(true)
        }

        setError(null)

        const response = await apiFetch("http://127.0.0.1:8000/api/dashboard/trades")

        if (!response.ok) {
          throw new Error("Failed to fetch trades")
        }

        const data: TradesResponse = await response.json()

        setTrades((prev) => {
          const prevJson = JSON.stringify(prev)
          const nextJson = JSON.stringify(data.trades)
          return prevJson !== nextJson ? data.trades : prev
        })
      } catch (err) {
        setError(err instanceof Error ? err.message : "Unknown error")
      } finally {
        if (showLoading) {
          setLoading(false)
        }
      }
    }

    fetchTrades(true)

    const handlePortfolioUpdate = () => {
      fetchTrades(false)
    }

    window.addEventListener("portfolio-data-updated", handlePortfolioUpdate)

    const intervalId = window.setInterval(() => {
      fetchTrades(false)
    }, 10000)

    return () => {
      window.removeEventListener("portfolio-data-updated", handlePortfolioUpdate)
      window.clearInterval(intervalId)
    }
  }, [])

  return (
    <div className="space-y-6">
      <header className="space-y-2">
        <div className="flex items-center gap-3">
          <h1 className="text-3xl font-bold tracking-tight text-slate-900">
            Trades
          </h1>
          <Badge variant="secondary" className="rounded-full">
            Execution History
          </Badge>
        </div>
        <p className="text-slate-600">
          Recent buy and sell actions generated by PortaAI.
        </p>
      </header>

      {error && (
        <Card className="rounded-2xl border-red-200 shadow-sm">
          <CardContent className="pt-6">
            <p className="font-medium text-red-600">Error: {error}</p>
          </CardContent>
        </Card>
      )}

      <Card className="rounded-2xl border-slate-200 shadow-sm">
        <CardHeader>
          <CardTitle>Recent Trades</CardTitle>
        </CardHeader>
        <CardContent>
          {loading ? (
            <p className="text-slate-600">Loading trades...</p>
          ) : (
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Asset</TableHead>
                  <TableHead>Action</TableHead>
                  <TableHead>Amount</TableHead>
                  <TableHead>Time</TableHead>
                  <TableHead>Status</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {trades.map((trade, index) => (
                  <TableRow key={`${trade.asset}-${index}`}>
                    <TableCell className="font-medium text-slate-900">
                      {trade.asset}
                    </TableCell>
                    <TableCell>
                      <ActionBadge action={trade.action} />
                    </TableCell>
                    <TableCell className="font-medium text-slate-800">
                      {formatCurrency(trade.amount)}
                    </TableCell>
                    <TableCell className="text-slate-600">
                      {trade.time}
                    </TableCell>
                    <TableCell>
                      <Badge className="rounded-full bg-cyan-600 hover:bg-cyan-700">
                        {trade.status}
                      </Badge>
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          )}
        </CardContent>
      </Card>

      <Card className="rounded-2xl border-slate-200 shadow-sm">
        <CardHeader>
          <CardTitle>Trade Summary</CardTitle>
        </CardHeader>
        <CardContent className="space-y-3 text-slate-600">
          <p>
            Each trade shown here is generated by the portfolio decision engine
            after combining model forecasts, sentiment signals, and allocation rules.
          </p>
          <p>
            In the current implementation, execution is simulated as part of
            paper trading.
          </p>
        </CardContent>
      </Card>
    </div>
  )
}